### PR TITLE
[WIP] feat(deps): Support 1.19.3

### PR DESCRIPTION
**Pull request by Norbiros**
I used #25 and fixed a few things, so it works on 1.19.3. I also added Polish translations.

### CODE REVIEW

**Comment by Felix14-v2** [comment]
Did you manage to make it work? It seems that I was doing something wrong, and I am getting this error
<details>
 <summary>ClassNotFoundException: io.github.ezforever.thatorthis.internal.ModInjector</summary>

```
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    at io.github.ezforever.thatorthis.internal.Bootstrap.&lt;clinit&gt;(Bootstrap.java:22)
    at io.github.ezforever.thatorthis.PreloadInitializer.onInitializing(PreloadInitializer.java:34)
    at io.github.ezforever.thatorthis.PreloadAdapter.&lt;clinit&gt;(PreloadAdapter.java:16)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:467)
    at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:439)
    at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:349)
    at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:112)
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
</details>

**Comment by Norbiros** [comment]
It worked for me... Are you using correct version?  With correct dependencies? I don't think I changed something that could cause this error.

**Comment by Felix14-v2** [comment]
Honestly, i've no idea... I'm new to this, so I just compiled your repository and it doesn't look like it worked. Maybe you can post your build here or make a release in your repo?

**Comment by Norbiros** [comment]
Strange... When I run it with `gradle runClient` it works, but If I compile it and run it in normal minecraft it doesn't work. I am trying to fix this error...

**Comment by Norbiros** [comment]
@SettingDust maybe you have idea how we can fix this problem?

**Comment by SettingDust** [comment]
https://github.com/FabricMC/fabric-loader/issues/682
As I mentioned, that's the reason of the PR is WIP.
The class loader isn't the one
In general, you can't make ThatOrThis works.
Mixin can't mixin the class that loaded. And FabricLoader should always load before the mixin(In my mind)
But in Quilt, there is api for this. You can try to develop this mod on Quilt and switch to Quilt that with fabric mod compatibility https://github.com/EZForever/ThatOrThis/issues/26

**Comment by Norbiros** [comment]
Okay. Thanks for help!

**Comment by Norbiros** [comment]
@SettingDust created a new [project](https://github.com/SettingDust/ModSets) which supports 1.19.2.

**Comment by SettingDust** [comment]
> @SettingDust created a new [project](https://github.com/SettingDust/ModSets) which supports 1.19.2.

It's in review on modrinth

**Comment by SettingDust** [comment]
> It's in review on modrinth

@Norbiros @Felix14-v2 Listed :)

**Pull request closed without merging**
